### ISSUE TITLE
Compiling the code

### ISSUE THREAD

**Issue by RChadwick7** [mossmann/im-me#4]
How do you compile the code? I assumed SDCC, but running the makefile caused errors. Do I need an older version of SDCC?

**Comment by Ivan275g4** [comment]
Have you figured out how to compile the code? I'm using a windows sdcc-3.8.0-x64 and I'm getting errors:

C:\>sdcc C:\specan\specan.c

In file included from C:\specan\specan.c:22:
C:\specan\/display.h:58:1: warning: "NOP" redefined
In file included from C:/Program Files/SDCC/bin/../include/mcs51/cc1110.h:29,
                 from C:\specan\specan.c:20:
C:/Program Files/SDCC/bin/../include/mcs51/compiler.h:92:1: error: this is the location of the previous definition
C:/Program Files/SDCC/bin/../include/stdio.h:86: error 91: extern definition for 'putchar' mismatches with declaration.
C:\specan\/display.h:103: error 177: previously defined here

**Comment by RChadwick7** [comment]
No, I never figured it out. Hopefully someone has, as the in-me is an ideal platform for quickly developing ideas.

**Comment by Ivan275g4** [comment]
I got it to compile without errors but have not tried to flash it. You need to use an older SDCC version, I believe it compiles with versions 2.9, 3.0, 3.1, 3.4, 3.5, 3.6 but the compiled file doesn't match the compiled file that the author made. That makes it a bit scary for me.  Maybe its because I'm using windows version of SDCC and author used Linux version, or maybe a sub version that i cant find like 3.0.2 or ???

**Comment by Ivan275g4** [comment]
After compiling it with 2.9.0 #5416 (Mar 22 2009) (MINGW32) it did flash it without problems.

**Comment by Ivan275g4** [comment]
After compiling it with 2.9.0 #5416 (Mar 22 2009) (MINGW32) it did flash it without problems. Its not working at 100% just yet, but maybe sometime I'll get to trying to make it work.

**Comment by kalirenegade** [comment]
so when i received this error i check out all the files containing the putchar and i removed all reference from C:/Program Files/SDCC/bin/../include/stdio.h and it compiled no problem you could also just remove the reference from display.h
